### ISSUE TITLE
Blank glossary term

### ISSUE THREAD

**Issue by cmajel** [GSA/pra.gov#105]
I noticed today that if I click `desk officer` on the "Get help with the PRA" page, it calls the flyout but does not provide a definition.

<img width="496" alt="Screen Shot 2019-04-16 at 3 43 41 PM" src="https://user-images.githubusercontent.com/2374206/56239258-735a4980-605e-11e9-83ec-456dfb32668e.png">

**Comment by hursey013** [comment]
Just pushed up a fix. Validate here once Federalist is done building: https://federalist-proxy.app.cloud.gov/preview/gsa/pra.gov/bh-visual-design/contact/
