### ISSUE TITLE
Remove undefined values from contact previews

### ISSUE THREAD

**Issue by cmajel** [GSA/pra.gov#110]
After adding more contacts to the agency search, I noticed that the empty values are shown as undefined. See the phone number and acronym in the second listing. 

Can we remove these?

<img width="756" alt="Screen Shot 2019-04-17 at 4 32 20 PM" src="https://user-images.githubusercontent.com/2374206/56320349-fac4bd00-6131-11e9-99c7-19586829d56d.png">

**Comment by opensso** [comment]
@cmajel  https://github.com/GSA/pra.gov/pull/121
