### ISSUE TITLE
Contact search returns results that do not match agency name

### ISSUE THREAD

**Issue by cmajel** [GSA/pra.gov#112]
When I search the word "bureau" the first result is for an agency without "bureau" in its name. It appears that the search is not just matching to agency names, but to anything in the preview listing. This could lead to unpredictable search results. 

<img width="825" alt="Screen Shot 2019-04-19 at 11 13 33 AM" src="https://user-images.githubusercontent.com/2374206/56430885-df72c280-6295-11e9-9216-3f3cfba4618e.png">

**Comment by hursey013** [comment]
I was including the `office` value in the search, however this has since been rewritten and now only uses the `agency` and `short` values.
