### ISSUE TITLE
Top item in side nav is blank/not displaying 

### ISSUE THREAD

**Issue by amandacostello** [GSA/pra.gov#117]
![Screen Shot 2019-04-23 at 11 18 05 AM](https://user-images.githubusercontent.com/45800660/56598155-93878c80-65b9-11e9-937d-1c5578b71796.png)

**Comment by hursey013** [comment]
Are you still seeing this, I thought I fixed it. Can you send me a link to where you see it?

**Comment by amandacostello** [comment]
Yep! Here: https://federalist-proxy.app.cloud.gov/preview/gsa/pra.gov/bh-visual-design/do-i-need-clearance/

Let me know if I'm using an older URL, too!

**Comment by amandacostello** [comment]
Aha! I was using an old URL. Disregard, it looks fine! :)
