### ISSUE TITLE
Point users to appropriate contact based on where they are in the process

### ISSUE THREAD

**Issue by qmanderson1** [GSA/pra.gov#38]
Users wanted to know where to go for help for their specific question or stage of the process. Point them to the appropriate point of contact based on where they are in the clearance process.

**Comment by cmajel** [comment]
@qmanderson1 I added this language which has been edited by OIRA. Do you think this satisfies this issue?
https://federalist-proxy.app.cloud.gov/site/gsa/pra.gov/contact/

**Comment by qmanderson1** [comment]
Yes, I just read it. That should solve it. Thanks! @cmajel
