### ISSUE TITLE
Make clearance <> approval consistent 

### ISSUE THREAD

**Issue by cmajel** [GSA/pra.gov#53]
Per convo this morning, we'll do a pass and make "PRA approval" and "PRA clearance" consistent.

@amandacostello can you update with what term you'd like to use?

**Comment by amandacostello** [comment]
Talked with Nick on 4/4 and he said that approval is generally used. Is there a way to highlight all uses of "Clearance" on the site? It needs to stay in _some_ places, but most will change.
