### ISSUE TITLE
Add in Part A summary quesitons

### ISSUE THREAD

**Issue by amandacostello** [GSA/pra.gov#86]
This content is ready for the web: https://docs.google.com/document/d/1qqFMr9ZfGKIe2ZFx8UD2g9X6wR8YWnEgX876Asxhtlw/edit?usp=sharing

It's a plain language summary of the 18 questions in Part A of the supporting statement. Originally, it was made to be included at the bottom of the clearance-process/supporting-statement/ 

But that makes the page SO LONG!

Could this be another page in the approval process? A sub page under Supporting Statement (already a sub page)? Would love extra thoughts on this!

**Comment by qmanderson1** [comment]
This looks great! I added a couple of suggestions in the doc.

**Comment by cmajel** [comment]
I added a few comments but in general, I think this would be great as a stand alone "Part A questions" page. 

A few thoughts for the future:
* Should we have a similar page with the Part B questions? I also sometimes see a Part C referenced in completed packages. 
* Should we include links within these pages to an additional resources page to show how users can find examples of completed packages via reginfo?

**Comment by amandacostello** [comment]
Standalone page has been added!
