### ISSUE TITLE
Document how to add/remove subpages

### ISSUE THREAD

**Issue by cmajel** [GSA/pra.gov#89]
We should provide a write up that includes:
* how to add / remove sub pages within a section
* how to find links that need to be updated
* how to test your edits

**Comment by hodbadger** [comment]
Can I help? I'm trying to get some experience in writing technical documentation.

**Comment by hursey013** [comment]
Documented adding and removing subpages: https://github.com/GSA/pra.gov/wiki/Add-or-remove-a-subpage
